"""
api/export.py — Markdown → PDF export endpoint.

POST /api/export
Body: {"markdown": "...", "topic": "..."}

Returns a styled, downloadable PDF using WeasyPrint.
Falls back to ReportLab if WeasyPrint is unavailable.
"""

import io
import re
import tempfile
from datetime import datetime

from fastapi import APIRouter
from fastapi.responses import Response
from pydantic import BaseModel

router = APIRouter()


class ExportRequest(BaseModel):
    markdown: str
    topic: str = "Research Report"


@router.post("/export")
async def export_pdf(req: ExportRequest):
    """Convert a Markdown report to a styled PDF and return it as a download."""
    html = _markdown_to_html(req.markdown, req.topic)
    pdf_bytes = _html_to_pdf(html)

    safe_name = re.sub(r"[^a-zA-Z0-9_-]", "-", req.topic)[:50]
    filename = f"research-{safe_name}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ── Markdown → HTML ──────────────────────────────────────────────────────────

CSS = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: 'Inter', sans-serif;
  font-size: 11pt;
  line-height: 1.7;
  color: #1a1a1a;
  max-width: 720px;
  margin: 0 auto;
  padding: 40px 48px;
}

.report-header {
  border-bottom: 2px solid #0F6E56;
  padding-bottom: 16px;
  margin-bottom: 32px;
}

.report-header h1 {
  font-size: 22pt;
  font-weight: 600;
  color: #0F6E56;
  margin-bottom: 4px;
}

.report-meta {
  font-size: 9pt;
  color: #666;
}

h2 {
  font-size: 14pt;
  font-weight: 600;
  color: #0F6E56;
  margin: 28px 0 10px;
  padding-bottom: 4px;
  border-bottom: 0.5px solid #d0ede6;
}

h3 {
  font-size: 12pt;
  font-weight: 600;
  color: #1a1a1a;
  margin: 20px 0 8px;
}

p { margin-bottom: 10px; }

ul, ol {
  padding-left: 22px;
  margin-bottom: 10px;
}

li { margin-bottom: 4px; }

strong { font-weight: 600; }

blockquote {
  border-left: 3px solid #0F6E56;
  padding-left: 14px;
  color: #555;
  font-style: italic;
  margin: 12px 0;
}

code {
  font-family: 'Courier New', monospace;
  font-size: 9pt;
  background: #f4f4f4;
  padding: 1px 4px;
  border-radius: 3px;
}

pre {
  background: #f4f4f4;
  padding: 12px;
  border-radius: 4px;
  overflow-x: auto;
  margin-bottom: 12px;
}

pre code { background: none; padding: 0; }

.footer {
  margin-top: 40px;
  padding-top: 12px;
  border-top: 0.5px solid #ddd;
  font-size: 8pt;
  color: #999;
  text-align: center;
}
"""


def _markdown_to_html(md: str, topic: str) -> str:
    """Convert Markdown to full HTML document with styling."""
    body = _parse_md(md)
    date_str = datetime.now().strftime("%B %d, %Y")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>{CSS}</style>
</head>
<body>
  <div class="report-header">
    <div class="report-meta">Autonomous Research Assistant &nbsp;·&nbsp; {date_str}</div>
  </div>
  {body}
  <div class="footer">
    Generated by Autonomous Research Assistant &nbsp;·&nbsp; {date_str}
  </div>
</body>
</html>"""


def _parse_md(md: str) -> str:
    """Minimal Markdown → HTML converter (covers the report's subset)."""
    lines = md.split("\n")
    html_parts = []
    i = 0

    while i < len(lines):
        line = lines[i]

        if line.startswith("### "):
            html_parts.append(f"<h3>{_inline(line[4:])}</h3>")
        elif line.startswith("## "):
            html_parts.append(f"<h2>{_inline(line[3:])}</h2>")
        elif line.startswith("# "):
            html_parts.append(f"<h1 style='font-size:20pt;font-weight:600;margin-bottom:8px'>{_inline(line[2:])}</h1>")
        elif line.startswith("> "):
            html_parts.append(f"<blockquote>{_inline(line[2:])}</blockquote>")
        elif line.startswith("- ") or line.startswith("* "):
            items = []
            while i < len(lines) and (lines[i].startswith("- ") or lines[i].startswith("* ")):
                items.append(f"<li>{_inline(lines[i][2:])}</li>")
                i += 1
            html_parts.append("<ul>" + "".join(items) + "</ul>")
            continue
        elif re.match(r"^\d+\. ", line):
            items = []
            while i < len(lines) and re.match(r"^\d+\. ", lines[i]):
                items.append(f"<li>{_inline(re.sub(r'^\d+\. ', '', lines[i]))}</li>")
                i += 1
            html_parts.append("<ol>" + "".join(items) + "</ol>")
            continue
        elif line.strip() == "":
            html_parts.append("")
        else:
            html_parts.append(f"<p>{_inline(line)}</p>")

        i += 1

    return "\n".join(html_parts)


def _inline(text: str) -> str:
    """Apply inline Markdown formatting."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*",     r"<em>\1</em>", text)
    text = re.sub(r"`(.+?)`",       r"<code>\1</code>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    return text


# ── HTML → PDF ───────────────────────────────────────────────────────────────

def _html_to_pdf(html: str) -> bytes:
    """Try WeasyPrint first, fall back to a basic ReportLab PDF."""
    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        pass

    try:
        return _reportlab_fallback(html)
    except Exception as e:
        raise RuntimeError(f"PDF generation failed: {e}. Install weasyprint or reportlab.")


def _reportlab_fallback(html: str) -> bytes:
    """
    Minimal PDF using ReportLab when WeasyPrint isn't available.
    Strips HTML tags and produces a plain text PDF.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.units import cm
    from reportlab.lib import colors

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    story = []

    # Strip HTML and render as paragraphs
    text = re.sub(r"<[^>]+>", " ", html)
    for line in text.split("\n"):
        line = line.strip()
        if line:
            story.append(Paragraph(line, styles["Normal"]))
            story.append(Spacer(1, 4))

    doc.build(story)
    return buf.getvalue()
